### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by epsilon-0** [solusipse/fiche#100]
I really love the whole program, thanks a lot for making it.

I am porting it to OpenBSD and am wondering if `pledge` and `unviel` PR will be given any consideration.

**Comment by immanuelfodor** [comment]
It seems it's not :(

**Comment by epsilon-0** [comment]
@immanuelfodor Indeed, I wrote up a different pastebin based on this, https://github.com/PurritoBin/PurritoBin
its faster in the sense that it doesn't rely on the socket timeout.
