### ISSUE TITLE
Cannot curl without a / at the end

### ISSUE THREAD

**Issue by narukeh** [solusipse/fiche#119]
i used the suggested nginx config

i can oppen the file in the browser

but i cannot curl the generated url, i get a error 301, says that its moved permanently

when i do `curl -L` on the generated url, i can print the file

when i add a `/` to the generated url i can `curl` without a `-L`

----

### Solution Ideas

Either make fiche to generate URLs with a `/` at the end, or edit the nginx config example.

**Comment by narukeh** [comment]
i tried to make a quick fix:
```diff
diff --git a/fiche.c b/fiche.c
index 99d140d..9caf53c 100644
--- a/fiche.c
+++ b/fiche.c
@@ -659,7 +659,7 @@ static void *handle_connection(void *args) {
         const size_t len = strlen(c->settings->domain) + strlen(slug) + 3;

         char url[len];
-        snprintf(url, len, "%s%s%s%s", c->settings->domain, "/", slug, "\n");
+        snprintf(url, len, "%s%s%s%s", c->settings->domain, "/", slug, "/\n");

         // Send the response
         write(c->socket, url, len);
```
but then i would get no new line
i also tried this way:
```diff
diff --git a/fiche.c b/fiche.c
index 99d140d..9caf53c 100644
--- a/fiche.c
+++ b/fiche.c
@@ -659,7 +659,7 @@ static void *handle_connection(void *args) {
         const size_t len = strlen(c->settings->domain) + strlen(slug) + 3;

         char url[len];
-        snprintf(url, len, "%s%s%s%s", c->settings->domain, "/", slug, "\n");
+        snprintf(url, len, "%s%s%s%s", c->settings->domain, "/", slug, "/", "/\n");

         // Send the response
         write(c->socket, url, len);
```
but it had the same effect...no new line at the end.
(im not good at either c nor nginx)

**Comment by solusipse** [comment]
You can use a rewrite like `rewrite ^([^.]*)$ /$1/;`
