### ISSUE TITLE
[rfe] improvements - chroot, privsep, syslog

### ISSUE THREAD

**Issue by jirib** [solusipse/fiche#12]
- chroot to a dir after startup where it saves files.
- split into multiple processes - to bind port, to save files, to log
- log to syslog

Idea could be copied from http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/httpd/ which runs as least as 3 processes.

**Comment by solusipse** [comment]
I've rewritten the whole thing recently and I don't want to overcomplicate things with the current version, so we're probably won't implement these, sorry.

As for
>log to syslog

this can be achieved if fiche is ran by an init system.

Thanks.
