### ISSUE TITLE
can't run with -6

### ISSUE THREAD

**Issue by roughnecks** [solusipse/fiche#122]
Hello,

if I try to run fiche with IPv6 I'm getting the help message saying that:

` usage: fiche [-dLpsSoBulbw]` - as you can see there's no "6" option.
I compiled from git

Other question. How do I bind to IPv6 only? How's the address format accepted by `-L`?

Thanks

**Comment by roughnecks** [comment]
Was able to run some tests with -L:

`/usr/local/bin/fiche -d termbin.wood...t.space -L :: -p 9999 -o /var/lib/fiche/code -s 6 -l /var/log/fiche.log -S`

```
netstat -lnp | grep fiche
tcp        0      0 255.255.255.255:9999    0.0.0.0:*               LISTEN      868749/fiche
```

```
echo "123" | ncat wood...t.space 9999
Ncat: Connection refused.
```

**Comment by roughnecks** [comment]
Anyone here?

**Comment by samip5** [comment]
https://github.com/solusipse/fiche/blob/master/fiche.c#L446

Hardcoded to IPv4-only.

**Comment by roughnecks** [comment]
I see. I'm closing this anyway, since yours was the only answer in 9 months.
Thanks
