### ISSUE TITLE
buffer size assistance

### ISSUE THREAD

**Issue by jungle-boogie** [solusipse/fiche#27]
Hello,

How big of a buffer do I need to have this file loaded?
http://termbin.com/o6cc

**Comment by solusipse** [comment]
Min `70469` bytes, but I would recommend a buffer size that's a power of 2, so let's say `131,072`. Buffer takes everything at once, see #24 for explanations.

**Comment by jungle-boogie** [comment]
That did it! Thanks for the tip!
