### ISSUE TITLE
seg fault with log

### ISSUE THREAD

**Issue by jungle-boogie** [solusipse/fiche#28]
Interesting seg fault with this:
http://termbin.com/kt68

Why does the close of fiche not report the `-l` location?

**Comment by solusipse** [comment]
Does user `www` exist?

**Comment by jungle-boogie** [comment]
Hi @solusipse,

Yes, www exists and that's what nginx uses.

Without the -l /path/to/log, fiche works just fine.

**Comment by solusipse** [comment]
That's right, it should be fixed, thanks!

**Comment by solusipse** [comment]
I've rewritten the whole code base. It might be considered to be fixed. Thanks for reporting!
