### ISSUE TITLE
file types force downloads

### ISSUE THREAD

**Issue by jungle-boogie** [solusipse/fiche#29]
Hello,

Fiche will force a download of the file instead of displaying it in the browser. Nginix can display the file just fine on its own.

    % file test-text.txt
    test-text.txt: ASCII text, with CRLF, CR, LF line terminators, with escape sequences, with overstriking

replication steps:

    script test.txt
    ls -l
    date
    exit
    cat test.txt | nc termbin.com 9999

**Comment by jungle-boogie** [comment]
Again, my mistake and I overlooked the browsers I used during the tests.

Chrome forces the download whereas Firefox will display the file contents.

Any input on what causes chrome to force the download with the file type above?

**Comment by solusipse** [comment]
Thanks. I'm afraid it has nothing to do with fiche, check nginx settings.
