### ISSUE TITLE
pid file?

### ISSUE THREAD

**Issue by jungle-boogie** [solusipse/fiche#30]
Hello,

I'd like to have fiche run as a daemon on my freebsd system and I'm reading this document:
https://www.freebsd.org/doc/en/articles/rc-scripting/article.html

I have a crude but functioning script located at `/usr/local/etc/rc.d/fiche` and I can start it up with `onestart`. The problem is stopping it with `sudo service fiche stop` because I don't think a pid file is created by fiche. Is a pid file actually created? I don't see anything in the typical `/var/run/fiche.pid` section. Meanwhile, my rc.d script must have a location to even start the script. 

Error:

    % sudo service fiche stop
    fiche not running? (check /var/run/fiche.pid).

Thanks!

**Comment by solusipse** [comment]
It's up to you to create this file with your daemon script, if I understand correctly, see http://unix.stackexchange.com/questions/137519/start-stop-daemon-not-working-as-expected-no-pid-file-was-written. fiche does not create any socket or pid files by design.
