### ISSUE TITLE
HTTPS support without config file

### ISSUE THREAD

**Issue by jeaye** [solusipse/fiche#33]
When using just the command line, we can specify `-d foo.com` and fiche just adds `http://` to the front of it. How about a new flag which says that we want to use `https://`?

**Comment by solusipse** [comment]
That's cool idea, thanks.

**Comment by solusipse** [comment]
Done. Thanks!

**Comment by sbrl** [comment]
How can I use this enhancement?

**Comment by solusipse** [comment]
Just add `-S` flag, e.g. `fiche -d domain.com -S`.

**Comment by sbrl** [comment]
@solusipse Thanks!

**Comment by sentriz** [comment]
is this feature gone?

**Comment by solusipse** [comment]
@sentriz re-added, thanks for the reminder!

**Comment by sbrl** [comment]
Awesome, thanks! You forgot to update the help / README though

**Comment by solusipse** [comment]
@sbrl Yeah, sorry! Fixed, thank you! :smile: Btw, there are still some features that I need to redesign and add to the new version. If you need anything, please let me know!

**Comment by sbrl** [comment]
Awesome, thanks - that was fast! :racing_car: I'll be sure to let you know if there's anything I think of :smiley_cat:

**Comment by sentriz** [comment]
@solusipse very nice, thank you
