### ISSUE TITLE
Subfolder support?

### ISSUE THREAD

**Issue by sbrl** [solusipse/fiche#35]
Can I run the webserver address for fiche under a subfolder like `https://example.com/bin`? It would make setting it up much more convenient. I would still have the main listener on `example.com:9999`.

**Comment by solusipse** [comment]
It's possible and it depends on your server's configuration.

**Comment by sbrl** [comment]
Thanks! I've just worked out how to do it.

**Comment by andyforceno** [comment]
I know this is an old closed issue, but how can this be done with nginx? I found that if I set nginx to serve from /fiche, fiche still outputs the url with just the root folder, e.g. http://www.example.com/fyt

**Comment by sbrl** [comment]
For those wondering how it's done, you set the `-d` param like so: `./fiche -d bobsrockets.com/path/to/subfolder`, and set the `-o` output directory normally.
