### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by jamesbeedy** [solusipse/fiche#36]
Hows it going? Could you please tag a 1.0, or latest release of fiche? Thanks!

**Comment by solusipse** [comment]
I'm going to rewrite some fragments soon. Then I'll make a release, thanks!

**Comment by solusipse** [comment]
I've just created a new release with rewritten codebase, but this isn't 1.0 yet. I'm going to add lacking features soon (there are just 3 minor features to add at the moment) and then I'll release 1.0 version. Thank you.
