### ISSUE TITLE
hack machine 

### ISSUE THREAD

**Issue by HazelFZ** [solusipse/fiche#39]
[root@iZ944ruexrfZ ~]# cat READ_THIS.txt 
Hi, please view: http://termbin.com/nvfk for further information in regards to your files!

I hope it does not you done,however the domain is same as your main page!

**Comment by solusipse** [comment]
Nah, it wasn't us who got hacked. I was already contacted by admin being blackmailed, don't know current status of that. I guess I should make it nonpublic. Thanks.
