### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [solusipse/fiche#4]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "open a stream") ⇒ [save_log](https://github.com/solusipse/fiche/blob/157353707e17bc4c8ac4dd6743711bedb7a5a526/fiche.c#L178)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "print formatted output") ⇒ [display_info](https://github.com/solusipse/fiche/blob/157353707e17bc4c8ac4dd6743711bedb7a5a526/fiche.c#L196)

**Comment by solusipse** [comment]
Of course, doing that in aspect way is the better way, but I'm afraid this piece of software is too small to gain real benefits from it. Thanks for the links, it's very interesting.
Issue mentioned here was fixed by #23. Thanks.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Are there [a few update candidates](https://github.com/solusipse/fiche/blob/f76eea893134922fd8166f775a08252bea9b0fcb/fiche.c#L249 "Update candidate: load_list()") left over?
