### ISSUE TITLE
No error when trying to write to unwritable folder

### ISSUE THREAD

**Issue by sbrl** [solusipse/fiche#44]
I've just moved fiche to my new server, and it's stopped working.

If I run `echo test | netcat starbeamrainbowlabs.com 9999` against my server from my laptop, it hangs and doesn't do anything.

On the server if I run `netstat -peanut | grep -i fiche` then I get this:

```
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      998        2126201     31326/fiche     
tcp        0      0 5.196.73.75:9999        5.198.44.45:59898       CLOSE_WAIT  998        2126202     31326/fiche
```

There's a socket stuck in the TCP `CLOSE_WAIT` state. Hrm. Let's do some more investigation. What happens if I `CTRL+C` the command on my laptop and try again with just `netcat starbeamrainbowlabs.com 9999`?

```
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      998        2126201     31326/fiche     
tcp        0      0 5.196.73.75:9999        5.198.44.45:59898       CLOSE_WAIT  998        2126202     31326/fiche     
tcp        0      0 5.196.73.75:9999        5.198.44.45:59908       ESTABLISHED 998        2125786     31326/fiche
```

Hum. That can't be right. the old connection still hasn't been closed, according to the server. (Interestingly I also encountered #31 again too, although I suspect that's because of a timeout or something)  What about the laptop then? Let's `CTRL + C` and try a `sudo netstat -peanut | grep -i netcat` on the laptop.

```
me@laptop$ sudo netstat -peanut | grep -i netcat
me@laptop$ sudo netstat -peanut | grep -i nc
```

Nothing. So the laptop thinks the connection is closed, but the server appears to have other ideas.

I'm using the following fiche command:

```
/srv/fiche/fiche -u fiche -d starbeamrainbowlabs.com/bin -o /srv/www/bin -B 4096 -S -b /srv/fiche/fiche-bans.txt -l /srv/fiche/fiche-access.log
```
- Server `uname -a`: `Linux starbeamrainbowlabs.com 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Laptop `uname -a`: `Linux Snowflake 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
- Laptop `netcat`: `This is nc from the netcat-openbsd package. An alternative nc is available
  in the netcat-traditional package.
  usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
    [-P proxy_username] [-p source_port] [-q seconds] [-s source]
    [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
    [-x proxy_address[:port]] [destination] [port]`

I don't know how to retrieve my netcat version.

Thoughts?

**Comment by sbrl** [comment]
Yep, I'm still having this issue.

My netcat version (according to `apt show netcat`) is `1.10-41`.

**Comment by sbrl** [comment]
I've just (kinda) solved this one! This behaviour occurs if you ask fiche to write out to a folder that doesn't exist, or it doesn't have permission to write to or create. It ought to give at least _some_ clue that this is the problem.

**Comment by solusipse** [comment]
Thanks, this should be fixed.

**Comment by solusipse** [comment]
I've rewritten the whole code base. It was fixed during the process. Thank you for reporting that!

**Comment by sbrl** [comment]
Excellent, thanks :smiley_cat:
