### ISSUE TITLE
Error running "Sudo make install"

### ISSUE THREAD

**Issue by oidz1234** [solusipse/fiche#50]
Hello,

I get the following error when running the above command:

install -m 0755 fiche 
Makefile:12: recipe for target 'install' failed

Help.

**Comment by chasgames** [comment]
I also get the same problem

**Comment by solusipse** [comment]
Fixed, thanks! Makefile was messed up a bit. If one wants to install with prefix, he should do something like that `make install prefix=/foo/bar`.
