### ISSUE TITLE
Optional line numbering?

### ISSUE THREAD

**Issue by coaxial** [solusipse/fiche#51]
Hey, I love Fiche, it's so convenient!

I just wish it had optional line numbering à la GitHub. Sure I could insert via a pipe with sed, but then it messes copy/paste. I would be more convenient if it was in two separate colons. Would it be a feature that anyone else finds useful?

**Comment by tYYGH** [comment]
Copy-paste friendly:
nl | netcat …
text text text
text text
Ctrl+D

**Comment by sbrl** [comment]
Line numbering sounds a bit difficult to do without changing the original text. Perhaps a sort of web interface in a separate project to provide line numbering and syntax highlighting?

**Comment by TomDataworks** [comment]
If you want to have pretty line numbering, syntax highlighting, or any other type of fancy features... You should be able to use php or another language to provide a template, and URL rewriting in your web server.

**Comment by Evidlo** [comment]
You could also specify a different port for pastes intended to be colored, like 10000.

**Comment by solusipse** [comment]
I've created very basic script for serving pastes with line numbering and syntax colouring. To get beautified pastes use this subdomain: `l.termbin.com`.

E.g.:

Regular paste can be found there:
http://termbin.com/ydxh

Beautified version can be found there:
http://l.termbin.com/ydxh

Any paste can be served this way. Please let me know what you think about this solution.

**Comment by solusipse** [comment]
Added info about above to the readme file. Closing this now. Thanks for the idea!

**Comment by coaxial** [comment]
Thank you!

On 16 Oct 2017 10:34 AM, "solusipse" <notifications@github.com> wrote:

Added info about above to the readme file. Closing this now. Thanks for the
idea!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/solusipse/fiche/issues/51#issuecomment-336906204>, or mute
the thread

**Comment by Evidlo** [comment]
It would also be nice if uploads using the l.termbin.com domain automatically returned a line-numbered link.
i.e.

    echo foo | nc l.termbin.com 9999

Would return `http://l.termbin.com/xxxx`

**Comment by Evidlo** [comment]
Made a new issue for this: #68
