### ISSUE TITLE
Binding option

### ISSUE THREAD

**Issue by daftaupe** [solusipse/fiche#52]
Hello,

I don't know if this is still maintained, but anyway it would be cool to have a binding option, because now fiche is binding on *

Regards

**Comment by daftaupe** [comment]
Tried to fix that with #53.

**Comment by solusipse** [comment]
Hello. I'm very sorry, but I had to rewrite the whole code base. This also means that you have to adjust your fix to the new version if you still want to contribute. Sorry again!

**Comment by solusipse** [comment]
I'm closing this for now, please feel free to reopen if you decide to rework the PR.
