### ISSUE TITLE
Nginx subfolder support

### ISSUE THREAD

**Issue by andyforceno** [solusipse/fiche#58]
How can I have fiche generate urls with a subfolder, e.g. http://example.com/fiche/zksuj? I have nginx configured properly, but fiche still gives urls with just the root folder.

**Comment by solusipse** [comment]
@andyforceno you can use `-d` switch to achieve that:
```
fiche -d example.com/fiche
```

**Comment by andyforceno** [comment]
Oh, I was following that too literally, I though `-d` was for just the
FQDN. Unless I missed that in the documentation, it wasn't obvious. Thanks,
I'll give it a try.

**Comment by andyforceno** [comment]
Yeah, I missed it. Should have read the description for `-d` a little more carefully. Works, thanks.

**Comment by solusipse** [comment]
I've added more explicit example to the readme file. Thanks for the idea!
