### ISSUE TITLE
fiche snap

### ISSUE THREAD

**Issue by jamesbeedy** [solusipse/fiche#59]
I've started a fiche snap, it builds, and works as expected, I'm just stuck figuring out a path to get fiche to return the machine ip in the response, instead of "example.com".

https://github.com/jamesbeedy/fiche/blob/snapping/snap/snapcraft.yaml

About to look at snapping up the rust version, as there is a nice rust plugin for snapcraft.

To build the above snap, in the project root run `snapcraft`, then to install it locally, `sudo snap install fiche_0.1_amd64.snap --devmode`

**Comment by solusipse** [comment]
That's cool! Many thanks, I'll add it to the readme file.

>I'm just stuck figuring out a path to get fiche to return the machine ip in the response, instead of "example.com"

That is not possible automatically, but you could set an address using `-d` switch: https://github.com/solusipse/fiche#domain--d, e.g.:

```
fiche -d 127.0.0.1
```

**Comment by solusipse** [comment]
It seems that this repository no longer exists, please reopen this issue if you're still interested in doing this. Thank you!
