### ISSUE TITLE
Reconsider service architecture?

### ISSUE THREAD

**Issue by elfring** [solusipse/fiche#6]
[The current software](https://github.com/solusipse/fiche/blob/157353707e17bc4c8ac4dd6743711bedb7a5a526/fiche.c#L105 "Connection handling") implements [the strategy "Thread per Request"](http://lycog.com/distributed-systems/thread-per-request/ "multi-threading"). This approach can become inappropriate with increasing usage requirements.

Would you like to [consider also different service designs](http://kegel.com/c10k.html "The C10K problem")?

**Comment by solusipse** [comment]
I'm sorry to have you keep waiting so long. I benchmarked it, it works blazing fast and has minimal memory footprint even with much load. I'd rather keep things simple so I will not rebuild it, at least not in the main branch. Thank you anyway.

**Comment by elfring** [comment]
Do any [challenges around the C10K problem](http://kegel.com/c10k.html "Suggestions for more powerful software designs") matter for you?

**Comment by solusipse** [comment]
Service is up for a year now and there were only 15 000 requests during that time (including invalid ones). This approach seems to me like an overkill for such piece of software.
