### ISSUE TITLE
segfault: null-terminated string operations on null-terminated buffer 

### ISSUE THREAD

**Issue by buhman** [solusipse/fiche#63]
https://github.com/solusipse/fiche/blob/master/fiche.c#L562-L564
https://github.com/solusipse/fiche/blob/master/fiche.c#L763

I suggest fnprintf or, even better, fwrite.

**Comment by buhman** [comment]
If recv completely fills the buffer, fprintf will out-of-bounds memory access, causing a segfault (also interrupting other threads).

**Comment by buhman** [comment]
Might I also suggest not encouraging a 32MB stack allocation--you could instead read chunks up to buffer_size.

**Comment by solusipse** [comment]
Excellent point, thank you. I've decided to take a different approach though, since fnprintf is not standard and fwrite wouldn't stop at first null character spotted (and we of course want to limit pastes size as much as possible). Fixed in 6d292a3.
