### ISSUE TITLE
memory leak in dispatch_connection

### ISSUE THREAD

**Issue by buhman** [solusipse/fiche#64]
https://github.com/solusipse/fiche/blob/master/fiche.c#L509

You are leaking `sizeof struct fiche_connection` for every connection.

**Comment by buhman** [comment]
Ahh nevermind--it's bad style for a caller to expect the callee to free memory allocated by the caller.

**Comment by solusipse** [comment]
Hi! Thanks, but I'm afraid you're not right about these.

>You are leaking sizeof struct fiche_connection for every connection.

This is passed to another thread and freed there, e.g.:
https://github.com/solusipse/fiche/blob/master/fiche.c#L677

>Ahh nevermind--it's bad style for a caller to expect the callee to free memory allocated by the caller.

Have you noticed that this is done in another thread?

>The same odd pattern is used in generate_slug as well.

Have you noticed that `generate_slug` isn't doing the final cleanup, only the intermediate one when the buffer has to be reallocated with different size?

**Comment by buhman** [comment]
> Have you noticed that this is done in another thread?

No, that's even worse.

> isn't doing the final cleanup, only the intermediate one when the buffer has to be reallocated with different size?

Yes, that's also beyond terrible.

**Comment by solusipse** [comment]
Are you going to suggest any kind of solution? inb4 delete the project.

Btw, as for
>>Have you noticed that this is done in another thread?

>No, that's even worse.

just for your information, it cannot be freed in the main thread when it's being passed to a detached one (guess why). It would be also nice if you'd actually analysed the code before creating an issue.

**Comment by solusipse** [comment]
I guess not. I'm closing this.
