### ISSUE TITLE
Error after make

### ISSUE THREAD

**Issue by nnsense** [solusipse/fiche#65]
Hi
I'm on CentOS7 (but I've tried on Ubuntu as well), right after "make" I've got this:

	cc main.c fiche.c -pthread -O2 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -std=gnu11 -g -O0 -o fiche
	fiche.c: In function 'save_to_file':
	fiche.c:764:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
		 for (int i = 0; i < s->buffer_len; i++) {
				   ^

Any idea?

Thanks :)

**Comment by nnsense** [comment]
Sorry, I've just noticed that fiche actually compile, and that's just a warning.
I've find that out while trying a fix, changing this
`for (int i = 0; i < s->buffer_len; i++) {`
into this
`for (unsigned int i = 0; i < s->buffer_len; i++) {`

Thank you :)

**Comment by solusipse** [comment]
@nnnn20430 Thank you, you're of course right. This should be unsigned int or size_t, but it's actually easier and faster to always set last buffer element to zero and that's what I decided to do in 10129c83025214df7d9a9ef629835fba26410618.

**Comment by nnnn20430** [comment]
i just noticed that i was mentioned here, i think you meant nnsense instead of me
