### ISSUE TITLE
Allow uploading to l.termbin.com

### ISSUE THREAD

**Issue by Evidlo** [solusipse/fiche#68]
Uploading to `l.termbin.com` should be allowed, where the returned URL is already line-numbered.

i.e.

    echo foo | nc l.termbin.com 9999

Would return `http://l.termbin.com/xxxx`

**Comment by solusipse** [comment]
That would be cool but I don't see a feasible way to do that without binding to two addresses that are connected to different domains. Since I currently can run the server only on a single interface, I'm not able to provide this feature, sorry.

**Comment by Evidlo** [comment]
Couldn't you bind to another port?  9999 might return the plaintext link and 10000 would return the line numbered link.

**Comment by Evidlo** [comment]
@solusipse Would the above solution not work?

**Comment by kmahyyg** [comment]
Is `l.` subdomain service included in the fiche source code? I mean does this software have colorized and numbered feature itself?

**Comment by Evidlo** [comment]
Yes, you just have to manually prepend `l.`.

**Comment by Evidlo** [comment]
@kmahyyg I meant specifically for `termbin.com`.  I don't know if it works for self-hosting.

**Comment by solusipse** [comment]
@kmahyyg 
>Couldn't you bind to another port? 9999 might return the plaintext link and 10000 would return the line numbered link.

That would work but I'd need to check if we can safely run two instances of fiche on the same machine (my guess is that we can't) - thanks for the idea, I'll take a look at this when I'm less busy

@Evidlo to make it work for self-hosting you have to host your own colouring service using this script: https://github.com/solusipse/fiche/tree/master/extras/lines

**Comment by kmahyyg** [comment]
> @kmahyyg
> 
> > Couldn't you bind to another port? 9999 might return the plaintext link and 10000 would return the line numbered link.
> 
> That would work but I'd need to check if we can safely run two instances of fiche on the same machine (my guess is that we can't) - thanks for the idea, I'll take a look at this when I'm less busy
> 
> @Evidlo to make it work for self-hosting you have to host your own colouring service using this script: https://github.com/solusipse/fiche/tree/master/extras/lines

Nope. You just need to do some reverse proxy on your host. That's what I did. I packed fiche into a docker and use a caddy as a reverse proxy. It works totally fine. Now I just need to do a few work to add the pygments in docker.

**Comment by kmahyyg** [comment]
And by the way, you could obvious rewrite it fully with Flask. It's really simple. This project inspired me to do such a pastebin without any database. Thank you very much.

**Comment by solusipse** [comment]
I'm not sure if I understood correctly - are you suggesting to isolate these two services?
>I packed fiche into a docker 

If you'd use the same location to store pastes from both instances you still could experience some problems (that's unlikely but not impossible). If you'd like to truly isolate these two, you'd have to add some extra stuff so it could be hosted by a single nginx service. I'm not interested in any of these solutions at the moment, sorry.

I'm glad you've found our little project inspirational, good luck with your pastebin! Cheers!
