### ISSUE TITLE
Crashes when buffer is set to 10485760 (10 Mb)

### ISSUE THREAD

**Issue by shadowlmd** [solusipse/fiche#74]
Fiche crashes when buffer is set to 10485760 (10 Mb) and someone tries to paste anything. What is the maximum allowed value for buffer size option (-B)?

**Comment by paboldin** [comment]
Buffer is allocated on the stack: https://github.com/solusipse/fiche/blob/master/fiche.c#L561
So any value you limit your stack too.

**Comment by solusipse** [comment]
@paboldin is right about this. If you'd like to have bigger buffer, you have to allocate it dynamically. I'm closing this issue, but let me know in case you need help with reworking the app to do so.

**Comment by shadowlmd** [comment]
@solusipse, if crashing is normal behavior, then it's ok. I would be nice if you covered this in README.md, so it would not be a surprise for anyone else. It's still not clear to me what is the biggest possible value to avoid crash, and I am not a programmer, so I have no idea how to rework it.

**Comment by solusipse** [comment]
We definitely should mention that somewhere, thanks for the suggestion
