### ISSUE TITLE
Stdout

### ISSUE THREAD

**Issue by gonzalo-** [solusipse/fiche#82]
Hello,

There is any way to make fiche more silent as a ,,daemon'' without all the output on stdout?

**Comment by solusipse** [comment]
Sorry for my late reply. You should be able to silence it by modifying these: https://github.com/solusipse/fiche/blob/master/fiche.c#L291-L317

**Comment by solusipse** [comment]
We may consider implementing some kind of switch that would silence all messages if more people will be interested in this

**Comment by gonzalo-** [comment]
If is a daemon, should be like that right? Send the output to a log not to stdout or atleast have that option?

**Comment by linxon** [comment]
@gonzalo- If you open `man start-stop-daemon`:

```
-1, --stdout logfile
             Redirect the standard output of the process to logfile when started with -background.  The logfile Must be an absolute pathname, but relative to the path optionally given
             with -r, --chroot.  The logfile can also be a named pipe.

-2, --stderr logfile
             Redirect the standard error of the process to logfile when started with -background.  The logfile must be an absolute pathname, but relative to the path optionally given with
             -r, --chroot.  The logfile can also be a named pipe.

```

**Comment by gonzalo-** [comment]
@linxon I am not using loonix.
