### ISSUE TITLE
replace gittip by liberapay

### ISSUE THREAD

**Issue by davidak** [solusipse/fiche#85]
Gittip, later Gratipay has shut down.

https://gratipay.news/the-end-cbfba8f50981

There is a fork, [Liberapay](https://liberapay.com/). Gratipay has hand their asset's over to them.

I also use Liberapay sucessfully, so i can reccommend that!

**Comment by solusipse** [comment]
Thanks for the suggestion! To be honest I've never received any donation through gitpay and I forgot we have that link on the website. I'm going to remove it in a moment.

It seems to me that Liberapay is something similar to Patreon. With my current level of involvement into this project I feel it's more appropriate to ask for one time donations using ko-fi. I'll create an account for that when I'm less busy
