### ISSUE TITLE
FreeBSD installation instructions

### ISSUE THREAD

**Issue by zi0r** [solusipse/fiche#86]
I've added fiche to the [FreeBSD Ports tree](https://www.freshports.org/net/fiche).

```
To install the port: cd /usr/ports/net/fiche/ && make install clean
To add the package: pkg install fiche
```

**Comment by solusipse** [comment]
Awesome, thank you! I've added mention about this to our readme: https://github.com/solusipse/fiche/commit/4bba916e0f4a54d98a3947df7e2d0714d92a8bab
