### ISSUE TITLE
[Tech support] Colored and numberer feature not working

### ISSUE THREAD

**Issue by kmahyyg** [solusipse/fiche#89]
I self-hosted the latest version of fiche.

I use [Caddy](https://caddyserver.com) as my webserver.

```yaml
https://example.com, https://l.example.com {
  timeouts none
  tls my@mymail.com
  root /to/path/codes
  index index.txt index.html
}
```

However, after I manually prepend `l.` , it will still output plain text without any colored or numbered content.

cc #68 @Evidlo

**Comment by solusipse** [comment]
You have to self-host the colouring service as well. You can use our script: https://github.com/solusipse/fiche/tree/master/extras/lines
Let me know if you need further help
